### ISSUE TITLE
Check for `module.process.main` is failing on CI

### ISSUE THREAD

**Issue by zeke** [MarshallOfSound/electron-DefinitelyTyped#1]
https://github.com/electron/electron/pull/7857
https://travis-ci.org/electron/electron/jobs/176476635

```
/home/travis/build/electron/electron/node_modules/electron-definitelytyped/lib/master-interfaces.js:17
    if (module.process.main && module.process.renderer) {
                      ^
TypeError: Cannot read property 'main' of undefined
    at /home/travis/build/electron/electron/node_modules/electron-definitelytyped/lib/master-interfaces.js:17:23
    at Array.forEach (native)
    at module.exports.API.forEach (/home/travis/build/electron/electron/node_modules/electron-definitelytyped/lib/master-interfaces.js:13:7)
    at module.exports.API.sort.forEach.Object.keys.forEach (/home/travis/build/electron/electron/node_modules/electron-definitelytyped/index.js:21:3)
    at Object.<anonymous> (/home/travis/build/electron/electron/node_modules/electron-definitelytyped/cli.js:36:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.6.2/bin/node" "/home/travis/build/electron/electron/node_modules/.bin/npm" "run" "generate-dts"
```

**Comment by zeke** [comment]
It looks like this check has been added: https://github.com/MarshallOfSound/electron-DefinitelyTyped/blob/f9334d30bb73a838e278995a6a4966a0289dd363/lib/master-interfaces.js#L17-L20

@MarshallOfSound do you want to cut a new release and bump the version in https://github.com/electron/electron/pull/7857

Or I'd be happy to do so if you want to give me GitHub/npm access :)

**Comment by MarshallOfSound** [comment]
`0.0.8` has been published with this fix and a locked linter version 👍 Also gave you github + npm access.  Do you want to maybe even move this to the electron org?

**Comment by zeke** [comment]
🍰 

Updated https://github.com/electron/electron/pull/7857

Yeah let's move it to the electron org! Thanks for offering.
